import type {
  ExecutionContext,
  ExecutionContextInput,
  LifecycleContext,
  LifecycleContextInput,
  RoutingContext,
  RoutingContextInput,
  TaskExecutionView,
  TaskListFilters,
} from './types.js';

export function createLifecycleContext({
  agentId,
  appId,
  source,
  describeSelf,
  listInstalledApps,
  listAvailableApps,
  listModelProviders,
  createMemoryScope,
}: LifecycleContextInput): LifecycleContext {
  return {
    agentId,
    appId,
    source,
    self: {
      describe: describeSelf,
    },
    apps: {
      listInstalled: listInstalledApps,
      listAvailable: listAvailableApps,
    },
    models: {
      list: listModelProviders,
    },
    memory: {
      agent: createMemoryScope('agent'),
      app: createMemoryScope({ kind: 'app', id: appId }),
      scope: (kind, id = null) => createMemoryScope({ kind, id }),
    },
  };
}

export function createRoutingContext({
  agentId,
  appId,
  signal,
  policy,
  describeSelf,
  listInstalledApps,
  listAvailableApps,
  listTasks,
  getTask,
  findResumableTask,
  taskInbox,
  createMemoryScope,
}: RoutingContextInput): RoutingContext {
  return {
    agentId,
    appId,
    signal,
    policy,
    self: {
      describe: describeSelf,
    },
    apps: {
      listInstalled: listInstalledApps,
      listAvailable: listAvailableApps,
    },
    tasks: {
      list: (filters: TaskListFilters = {}) => listTasks({
        ...filters,
        appId: filters.appId ?? appId,
      }),
      get: (taskId: string) => getTask(taskId),
      findResumable: (nextSignal = signal, filters: TaskListFilters = {}) => findResumableTask(nextSignal, {
        ...filters,
        appId: filters.appId ?? appId,
      }),
      inbox: taskInbox,
    },
    memory: {
      agent: createMemoryScope('agent'),
      app: createMemoryScope({ kind: 'app', id: appId }),
      task: (taskId) => createMemoryScope({ kind: 'task', id: taskId }),
      conversation: (conversationId) => createMemoryScope({ kind: 'conversation', id: conversationId }),
      scope: (kind, id = null) => createMemoryScope({ kind, id }),
    },
  };
}

export function createExecutionContext({
  agentId,
  appId,
  task,
  signal,
  policy,
  describeConversation,
  completeTask,
  waitForTask,
  waitForTasks,
  failTask,
  cancelTask,
  listTasks,
  getTask,
  updateTask,
  listTaskEvents,
  recordTaskEvent,
  listTaskInbox,
  peekTaskInbox,
  drainTaskInbox,
  clearTaskInbox,
  taskInboxSize,
  createMemoryScope,
  snapshotMemory,
  listTools,
  callTool,
  requestTool,
  listModelProviders,
  streamModel,
  generateModel,
  runModel,
  scheduleDelay,
  scheduleAt,
  scheduleRecurring,
  cancelSchedule,
  listSchedules,
  emitToSelf,
  publishSignal,
  publishReply,
  sendMessage,
  emitEvent,
  listInstalledApps,
  listAvailableApps,
  installApp,
  uninstallApp,
  describeSelf,
  listSelfHistory,
}: ExecutionContextInput): ExecutionContext {
  const taskView: TaskExecutionView = {
    ...task,
    get: () => getTask(task.id),
    update: updateTask,
    events: listTaskEvents,
    record: recordTaskEvent,
    inbox: {
      list: listTaskInbox,
      peek: peekTaskInbox,
      drain: drainTaskInbox,
      clear: clearTaskInbox,
      size: taskInboxSize,
    },
    wait: waitForTask,
    awaitSignal: waitForTask,
    awaitTasks: waitForTasks,
    waitForTasks,
    complete: completeTask,
    fail: failTask,
    cancel: cancelTask,
  };

  return {
    agentId,
    appId,
    task: taskView,
    tasks: {
      list: listTasks,
      get: getTask,
    },
    signal,
    conversation: {
      id: task.conversationId,
      describe: describeConversation,
    },
    policy,
    complete: completeTask,
    wait: waitForTask,
    waitForTasks,
    fail: failTask,
    cancel: cancelTask,
    memory: {
      agent: createMemoryScope('agent'),
      app: createMemoryScope({ kind: 'app', id: appId }),
      task: createMemoryScope({ kind: 'task', id: task.id }),
      conversation: createMemoryScope({ kind: 'conversation', id: task.conversationId }),
      scope: (kind, id = null) => createMemoryScope({ kind, id }),
      snapshot: snapshotMemory,
    },
    tools: {
      list: listTools,
      specs: listTools,
      call: callTool,
      request: requestTool,
    },
    models: {
      list: listModelProviders,
      stream: streamModel,
      generate: generateModel,
      run: runModel,
    },
    scheduler: {
      delay: scheduleDelay,
      at: scheduleAt,
      recurring: scheduleRecurring,
      cancel: cancelSchedule,
      list: listSchedules,
    },
    timers: {
      delay: scheduleDelay,
      at: scheduleAt,
      recurring: scheduleRecurring,
      cancel: cancelSchedule,
      list: listSchedules,
    },
    signals: {
      emitToSelf,
      publish: publishSignal,
      reply: publishReply,
      sendMessage,
      emitEvent,
    },
    apps: {
      listInstalled: listInstalledApps,
      listAvailable: listAvailableApps,
      install: installApp,
      uninstall: uninstallApp,
    },
    self: {
      describe: describeSelf,
      history: listSelfHistory,
    },
  };
}
